spring:
  security:
    user:
      name: dev_frontend_user
      password: ap1Fr0nt3nd_2025
  datasource:
    primary:
      jdbc-url: jdbc:oracle:thin:@10.34.8.103:1521:sadev
      username: BUSMAN_USER
      password: USER_busman_2025
      driver-class-name: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        idle-timeout: 30000
        max-lifetime: 1800000
        pool-name: SAQABCMConsumerHikariCP
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: 10.34.7.170:9092

    consumer:
      group-id: dev._event.bcm_consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.Map
      listener:
        ack-mode: record

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.kafka: DEBUG

# VARIABLES de AMBIENTE PET de consumo interno
bcm-event-properties:
  url-base: http://10.34.7.172:4300
  user-url-base: bcm_db_user
  pasz-url-base: X9#%Su5tbe
  url-token: /api/Auth/login-by-token
  user-token: dev_api_user
  pasz-token: j@ARDJ8dzP
  token: 4903CE4F6A6336F7E060220A550708F3

